### ISSUE TITLE
Unable to convert 1.18.2 region chunks to level.Chunk

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#164]
I generated a fresh world and tried to load it with serverFramework example however everything around me was air, no errors in logs. Examples-provided world works fine. I was met with following panic:
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:github.com/Tnze/go-mc/level.ChunkFromSave(0xc000a65860, 0x100)
        /home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2-0.20220401165811-e00bb53f9efb/level/chunk.go:160 +0x689
```
That was generated with this code:
```go
func loadAllRegions(dir string) (*server.SimpleDim, error) {
	mcafiles, err := filepath.Glob(filepath.Join(dir, "r.*.*.mca"))
	if err != nil {
		return nil, err
	}
	dim := server.NewSimpleDim(256)
	for _, file := range mcafiles {
		var rx, rz int
		_, err := fmt.Sscanf(filepath.Base(file), "r.%d.%d.mca", &rx, &rz)
		if err != nil {
			return nil, err
		}
		err = loadAllChunks(dim, file, rx, rz)
		if err != nil {
			return nil, err
		}
	}
	return dim, nil
}
func loadAllChunks(dim *server.SimpleDim, file string, rx, rz int) error {
	r, err := region.Open(file)
	if err != nil {
		return err
	}
	defer r.Close()
	var c save.Chunk
	for x := 0; x < 32; x++ {
		for z := 0; z < 32; z++ {
			if !r.ExistSector(x, z) {
				continue
			}
			data, err := r.ReadSector(x, z)
			if err != nil {
				return err
			}
			if err := c.Load(data); err != nil {
				return err
			}
			chunk := level.ChunkFromSave(&c, 256)
			dim.LoadChunk(level.ChunkPos{X: rx<<5 + x, Z: rz<<5 + z}, chunk)
		}
	}
	return nil
}
```
What am I doing wrong or is there a bug?

**Comment by Tnze** [comment]
Can the official game load your chunks?

**Comment by maxsupermanhd** [comment]
Yes, official game created them and I can load world back up

**Comment by maxsupermanhd** [comment]
Ok, here is some more conversion issues:
```
panic: invalid length given for storage, got: 37 but expected: 29

goroutine 488 [running]:
github.com/Tnze/go-mc/level.NewBitStorage(0x7, 0x100, {0xc0000be3c0, 0x25, 0x25})
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2-0.20220401165811-e00bb53f9efb/level/bitstorage.go:50 +0x1b4
github.com/Tnze/go-mc/level.ChunkFromSave(0xc000526340, 0x40)
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2-0.20220401165811-e00bb53f9efb/level/chunk.go:179 +0x5bd
```
Got this panic while converting from 1.16 save.Chunk. Any idea what is wrong and how to fix it?

**Comment by maxsupermanhd** [comment]
Conversion above was performed with section count 32, setting it to 256 somehow solved issue. However I still want an explanation to it...

**Comment by Tnze** [comment]
Is this problem exist now?

**Comment by maxsupermanhd** [comment]
Problem is still here, now it shows following:
```
panic: invalid length given for storage, got: 0 but expected: 32

goroutine 3614 [running]:
github.com/Tnze/go-mc/level.NewBitStorage(0x8, 0x100, {0x102d8d8, 0x0, 0x0})
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2-0.20220520061216-8f9bf2710522/level/bitstorage.go:50 +0x1b4
github.com/Tnze/go-mc/level.ChunkFromSave(0xc0005482c0)
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2-0.20220520061216-8f9bf2710522/level/chunk.go:211 +0x125
github.com/maxsupermanhd/WebChunk/viewer.(*chunkLoader).sendChunk(0xbf2300?, {0x97c1c0?, 0xc00145a680?}, 0xc0005b9e50)
	/home/max/p/0mc/mcwebchunk/viewer/chunk.go:134 +0x11b
created by github.com/maxsupermanhd/WebChunk/viewer.(*chunkLoader).processChunkLoadingForPlayer
	/home/max/p/0mc/mcwebchunk/viewer/chunk.go:170 +0x53b
```
Produced upon calling `level.ChunkFromSave` with save.Chunk that got converted from level.Chunk

**Comment by maxsupermanhd** [comment]
Oh wait, maybe it is me not preserving heightmaps actually... Will come back after more testing

**Comment by maxsupermanhd** [comment]
So now I have problem with heightmaps, do I have to compute all 4 of them or is there a way to initialize empty one?

**Comment by maxsupermanhd** [comment]
Can you please provide me example of proper reading form packet to save.Chunk and back?

**Comment by Tnze** [comment]
I will take a look about that

**Comment by Tnze** [comment]
I think we can close this issue now.
You can use following command to upgrade the chunks.

```bash
java -jar server.jar --forceUpgrade
```
