### ISSUE TITLE
Failed to load palette of a valid chunk

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#239]
```
panic: invalid length given for storage, got: 342 but expected: 256

goroutine 137 [running]:
github.com/Tnze/go-mc/level.NewBitStorage(0x4, 0x1000, {0xc0005f7800, 0x156, 0x180})
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.19.2/level/bitstorage.go:52 +0x1b4
github.com/Tnze/go-mc/level.NewStatesPaletteContainerWithData(0xa44ca0?, {0xc0005f7800, 0x156, 0x180}, {0xc000f9b340, 0xe, 0xe?})
	/home/max/go/pkg/mod/github.com/!tnze/go-mc@v1.19.2/level/palette.go:66 +0x1af
```
File of the chunk attached (gzip compressed, type 1): [chunk.bin](https://github.com/Tnze/go-mc/files/11242397/chunk.gz)

**Comment by maxsupermanhd** [comment]
Here is spew.Dump of the section in question (panic raised at section of Y0)
```
(save.Section) {
   Y: (int8) 0,
   BlockStates: (struct { Palette []save.BlockState "nbt:\"palette\""; Data []uint64 "nbt:\"data\"" }) {
    Palette: ([]save.BlockState) (len=14 cap=14) {
     (save.BlockState) {
      Name: (string) (len=19) "minecraft:deepslate",
      Properties: (nbt.RawMessage) {axis:y}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:2}
     },
     (save.BlockState) {
      Name: (string) (len=13) "minecraft:air",
      Properties: (nbt.RawMessage) {}
     },
     (save.BlockState) {
      Name: (string) (len=15) "minecraft:stone",
      Properties: (nbt.RawMessage) {}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:12}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:10}
     },
     (save.BlockState) {
      Name: (string) (len=18) "minecraft:obsidian",
      Properties: (nbt.RawMessage) {}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:4}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:6}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:8}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:fire",
      Properties: (nbt.RawMessage) {age:3,east:false,north:false,south:false,up:false,west:false}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:14}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:lava",
      Properties: (nbt.RawMessage) {level:0}
     },
     (save.BlockState) {
      Name: (string) (len=14) "minecraft:fire",
      Properties: (nbt.RawMessage) {age:4,east:false,north:false,south:false,up:false,west:false}
     }
    },
    Data: ([]uint64) (len=342 cap=342) {
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 0,
     (uint64) 34359738368,
     (uint64) 144220741192124416,
     (uint64) 65539,
     (uint64) 70368782974976,
     (uint64) 3145794,
     (uint64) 180144055963879426,
     (uint64) 72127962782105600,
     (uint64) 2251799880794112,
     (uint64) 72057594037927938,
     (uint64) 108086459776370688,
     (uint64) 6755470308020224,
     (uint64) 103809024,
     (uint64) 0,
     (uint64) 108086391056891904,
     (uint64) 2251799813685248,
     (uint64) 72057594037929984,
     (uint64) 137442099200,
     (uint64) 5629499601324032,
     (uint64) 2199023262756,
     (uint64) 2199023256579,
     (uint64) 7784628224,
     (uint64) 4398046513152,
     (uint64) 2199092527106,
     (uint64) 72057664905019552,
     (uint64) 1099513726976,
     (uint64) 185773484696207424,
     (uint64) 2251799815782405,
     (uint64) 72567834584064,
     (uint64) 74314892785485824,
     (uint64) 10133101309069376,
     (uint64) 68719478784,
     (uint64) 72572062405920,
     (uint64) 7740604811264,
     (uint64) 1125902056423424,
     (uint64) 70439612317696,
     (uint64) 72346773112291392,
     (uint64) 1131399612467200,
     (uint64) 252201581280296968,
     (uint64) 74379762871604225,
     (uint64) 74380003121370117,
     (uint64) 175921860446208,
     (uint64) 180143985096919040,
     (uint64) 74309396068368416,
     (uint64) 74311663741867047,
     (uint64) 72128100390996034,
     (uint64) 182395784975679488,
     (uint64) 70437465819136,
     (uint64) 72130161877877920,
     (uint64) 2257307346995202,
     (uint64) 324585728191299648,
     (uint64) 2322239494031429,
     (uint64) 74309464719795241,
     (uint64) 79979885938933824,
     (uint64) 10459724984158210,
     (uint64) 70370960934976,
     (uint64) 72060034820866048,
     (uint64) 70378417358848,
     (uint64) 180224320377718850,
     (uint64) 74379833462753285,
     (uint64) 74311666965161248,
     (uint64) 74485321086011456,
     (uint64) 5635067961477122,
     (uint64) 2322168624971813,
     (uint64) 74311663741995013,
     (uint64) 74379832458283010,
     (uint64) 149779940768811074,
     (uint64) 74382032555280386,
     (uint64) 74382030407893120,
     (uint64) 74385432125704258,
     (uint64) 190603710078978112,
     (uint64) 74382032555280453,
     (uint64) 74382032558653737,
     (uint64) 74379944067663938,
     (uint64) 324585730340882498,
     (uint64) 74382032555280453,
     (uint64) 74382030405805353,
     (uint64) 74350085747509314,
     (uint64) 10459725051201538,
     (uint64) 2324438517352453,
     (uint64) 2322239497348105,
     (uint64) 73324619365419074,
     (uint64) 185954906264305730,
     (uint64) 2324438517352608,
     (uint64) 74382032558490693,
     (uint64) 72130196170408002,
     (uint64) 74381963833641026,
     (uint64) 74382032555280450,
     (uint64) 74382032555349058,
     (uint64) 74382145367377986,
     (uint64) 190458574611220546,
     (uint64) 74382032555280453,
     (uint64) 74382032558531881,
     (uint64) 74385579366746178,
     (uint64) 190603710146086978,
     (uint64) 74382032555280450,
     (uint64) 74382032558662953,
     (uint64) 74382143392909378,
     (uint64) 190603710146086978,
     (uint64) 74382032555280449,
     (uint64) 74382032554337577,
     (uint64) 74381043881281602,
     (uint64) 406776492259870786,
     (uint64) 74382032555280517,
     (uint64) 74382032524973221,
     (uint64) 74381001766275138,
     (uint64) 74385331090163778,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382104495982658,
     (uint64) 192674090541189186,
     (uint64) 74382032555280450,
     (uint64) 74382032554337445,
     (uint64) 74381047102507074,
     (uint64) 338099896477354050,
     (uint64) 74382032555280453,
     (uint64) 74382032555389324,
     (uint64) 74381287724484674,
     (uint64) 194090261517764674,
     (uint64) 74382032555280450,
     (uint64) 74382032555389324,
     (uint64) 74382146717943874,
     (uint64) 193981409866614850,
     (uint64) 74382032555280450,
     (uint64) 74382032625840425,
     (uint64) 74385437494413378,
     (uint64) 146442925128091714,
     (uint64) 74382032555280450,
     (uint64) 74382032555280453,
     (uint64) 74382032555280450,
     (uint64) 149817326313736258,
     (uint64) 74382032555280450,
     (uint64) 74382032555388036,
     (uint64) 74382146475722818,
     (uint64) 194086962982881346,
     (uint64) 74382032555280450,
     (uint64) 74382032558666121,
     (uint64) 74382146717943874,
     (uint64) 410263043631548482,
     (uint64) 74382032555280450,
     (uint64) 74382032555389324,
     (uint64) 74382146717943874,
     (uint64) 194090261517764674,
     (uint64) 74382032555280450,
     (uint64) 74382032555389324,
     (uint64) 74456020155435074,
     (uint64) 37195449792268354,
     (uint64) 74382032555280449,
     (uint64) 74382032555444289,
     (uint64) 74382032554231874,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555443266,
     (uint64) 74382007928424514,
     (uint64) 49721086255892546,
     (uint64) 74382032555280450,
     (uint64) 74382032555258025,
     (uint64) 74381287721338946,
     (uint64) 49975073441908802,
     (uint64) 74382032555280450,
     (uint64) 74382032555585932,
     (uint64) 74382009278990402,
     (uint64) 194090261517764674,
     (uint64) 74382032555280450,
     (uint64) 74382032555389324,
     (uint64) 74382009278990402,
     (uint64) 401009553772185666,
     (uint64) 74382032555280609,
     (uint64) 74382032555280453,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 81318851414919234,
     (uint64) 74382032555280450,
     (uint64) 74382032555280417,
     (uint64) 74382031592687682,
     (uint64) 49975073441908802,
     (uint64) 74382032555280450,
     (uint64) 74382032555279525,
     (uint64) 74382244081371202,
     (uint64) 73224246811232322,
     (uint64) 74382032555280450,
     (uint64) 74382032555257893,
     (uint64) 74382008898357314,
     (uint64) 73259431183321154,
     (uint64) 74382032555280450,
     (uint64) 74382032555482156,
     (uint64) 74382032554231874,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74345748671563842,
     (uint64) 74382032555280450,
     (uint64) 74382032555279756,
     (uint64) 74382032520677442,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280449,
     (uint64) 74382032554231874,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280449,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 74382032555280450,
     (uint64) 67650
    }
   },
   Biomes: (struct { Palette []string "nbt:\"palette\""; Data []uint64 "nbt:\"data\"" }) {
    Palette: ([]string) (len=1 cap=1) {
     (string) (len=15) "windswept_hills"
    },
    Data: ([]uint64) {
    }
   },
   SkyLight: ([]uint8) {
   },
   BlockLight: ([]uint8) {
   }
  },
  ```
