### ISSUE TITLE
Example of how to send chunk data?

### ISSUE THREAD

**Issue by wildrun0** [Tnze/go-mc#98]
Hi! I'm trying to create a minecraft server based on your library(Thank you for your work), and I stuck with chunks. 
I would like to see examples of how to work with chunks through your library. How to create them (or get them through a ready-made level.dat file) and how to send them properly? 

Thanks a lot.

**Comment by Tnze** [comment]
Gladly know you are using my library.
Okay.

**Comment by Tnze** [comment]
The example is added to `chunk_test.go`. It is intended to read chunk from the save files and then packet as [Chunk Data](https://wiki.vg/Protocol#Chunk_Data).

https://github.com/Tnze/go-mc/blob/c1a2ac35ec6a5ef4d70f50e8afd3a83e6644d305/save/chunk_test.go#L59-L123

Sadly, due to the lack of some infrastructure, the palette can not be converted for the time being. I am sorry for that.
It's just fine when you are creating chunks manually and this example can be used well as a reference.

You get the idea.

> P.S. : The struct `save.Colume` and `save.Chunk` are not stable and some break changing may be done soon. It's not recommend to use them.

**Comment by wildrun0** [comment]
Wow, thank you. How can I import a "chunk" to get a Column struct? (I keep getting "undefined: Column" error). 
I'm just new to golang, trying to switch from python, so I apologize for a seemingly stupid question.

**Comment by wildrun0** [comment]
Oh, that sucks. I've tried to send a chunk and got this error:
```
panic: reflect: call of reflect.Value.Int on ptr Value

goroutine 18 [running]:
reflect.Value.Int(...)
        C:/Program Files/Go/src/reflect/value.go:999
github.com/Tnze/go-mc/net/packet.Ary.WriteTo(0xf2f148, 0xc00021f1c4, 0xe56860, 0xc00009a3b8, 0xf2e500, 0xc000088d80, 0xe79ca0, 0x0, 0xf2eb40)
        C:/Users/RTX_HYPER_PC/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210331110856-c1a2ac35ec6a/net/packet/util.go:14 +0x3ca
github.com/Tnze/go-mc/net/packet.Tuple.WriteTo(0xc00022b7b8, 0x4, 0x4, 0xf2e500, 0xc000088d80, 0x0, 0x0, 0x0)
        C:/Users/RTX_HYPER_PC/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210331110856-c1a2ac35ec6a/net/packet/util.go:68 +0xad
main.ExampleColumn_send(0xf312d8, 0xc00008e160, 0xf2e4c0, 0xc0000be000, 0xf2e900, 0xc00008e160, 0x0, 0xea6ffc, 0x16)
        C:/Users/RTX_HYPER_PC/Desktop/Minecraft-golang-server/chunk_worker.go:52 +0x94c
main.handlePlaying(0xf312d8, 0xc00008e160, 0xf2e4c0, 0xc0000be000, 0xf2e900, 0xc00008e160, 0x0, 0x242)
        C:/Users/RTX_HYPER_PC/Desktop/Minecraft-golang-server/main.go:253 +0xa91
main.acceptConn(0xf312d8, 0xc00008e160, 0xf2e4c0, 0xc0000be000, 0xf2e900, 0xc00008e160, 0x0)
        C:/Users/RTX_HYPER_PC/Desktop/Minecraft-golang-server/main.go:128 +0x1e9
created by main.main
        C:/Users/RTX_HYPER_PC/Desktop/Minecraft-golang-server/main.go:91 +0x175
exit status 2
```
There is some problems with .WriteTo(&buf) while creating a pk.Tuple

**Comment by Tnze** [comment]
Oh, it's not the problem of `pk.Tuple` but `pk.Ary`. May be it's a bug.

**Comment by Tnze** [comment]
The bug is fixed and more examples of Ary, Opt and Tuple is added.

And, I found some serious mistake in the previous codes. I'm sorry if they mislead you. The new version is right there, the same file, in latest commit.

**Comment by wildrun0** [comment]
Maybe I doing something wrong but I still have error with .WriteTo(&buf)

```
panic: reflect: call of reflect.Value.Len on ptr Value

goroutine 7 [running]:
reflect.Value.Len(0x596880, 0xc0000922d8, 0x16, 0x2)
        C:/Program Files/Go/src/reflect/value.go:1163 +0x19b
github.com/Tnze/go-mc/net/packet.Ary.WriteTo(0x5a8bc0, 0xc0000fac04, 0x596880, 0xc0000922d8, 0x66e7a0, 0xc000088660, 0x5bc8e0, 0x0, 0x66ede0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210401171643-c4c4ebeda80a/net/packet/util.go:28 +0xf4
github.com/Tnze/go-mc/net/packet.Tuple.WriteTo(0xc00021b770, 0x6, 0x6, 0x66e7a0, 0xc000088660, 0x0, 0x0, 0x0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210401171643-c4c4ebeda80a/net/packet/util.go:112 +0xad
main.ExampleColumn_send(0x6714d8, 0xc0000061a0, 0x66e760, 0xc000044120, 0x66eba0, 0xc0000061a0, 0x0, 0x5e71a0, 0x16)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/chunk_worker.go:56 +0x9f4
main.handlePlaying(0x6714d8, 0xc0000061a0, 0x66e760, 0xc000044120, 0x66eba0, 0xc0000061a0, 0x0, 0x242)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:249 +0xa91
main.acceptConn(0x6714d8, 0xc0000061a0, 0x66e760, 0xc000044120, 0x66eba0, 0xc0000061a0, 0x0)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:129 +0x1e9
created by main.main
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:92 +0x125
exit status 2
```

**Comment by ShirasawaSama** [comment]
@Tnze 1.12.2 chunk data serializer GKD.

**Comment by Tnze** [comment]
Pointer type is supported now at `Ary.WriteTo()`. 😶

**Comment by wildrun0** [comment]
Now I'm getting `panic: unsupported type map` when creating pk.Marshal

```
panic: unsupported type map

goroutine 6 [running]:
github.com/Tnze/go-mc/net/packet.nbtField.WriteTo(0xe26d20, 0xc000075410, 0xebd440, 0xc000075650, 0x1, 0x0, 0x0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402012951-c6255de74592/net/packet/types.go:439 +0xf7
github.com/Tnze/go-mc/net/packet.(*Builder).WriteField(0xc000075650, 0xc0000f95c0, 0x1, 0x1)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402012951-c6255de74592/net/packet/builder.go:11 +0x87
github.com/Tnze/go-mc/net/packet.Marshal(0x22, 0xc0000f97d0, 0xa, 0xa, 0xc000036e30, 0x5, 0x0, 0x0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402012951-c6255de74592/net/packet/packet.go:20 +0xae
main.ExampleColumn_send(0xec0178, 0xc000006198, 0xebd400, 0xc0000440c0, 0xebd840, 0xc000006198, 0x0, 0xe63d67, 0x16)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/chunk_worker.go:65 +0x688
main.handlePlaying(0xec0178, 0xc000006198, 0xebd400, 0xc0000440c0, 0xebd840, 0xc000006198, 0x0, 0x242)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:249 +0xa72
main.acceptConn(0xec0178, 0xc000006198, 0xebd400, 0xc0000440c0, 0xebd840, 0xc000006198, 0x0)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:130 +0x1e9
created by main.main
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:93 +0x185
exit status 2
```

**Comment by Tnze** [comment]
What's the content of `chunk_worker.go:65` ?

**Comment by wildrun0** [comment]
```
_ = pk.Marshal(
		0x22,
		pk.Int(chunkPos[0]),        // Chunk X
		pk.Int(chunkPos[1]),        // Chunk Y
		pk.Boolean(true),           // Full chunk
		PrimaryBitMask,             // PrimaryBitMask
		pk.NBT(c.Level.Heightmaps), // Heightmaps
		bal, pk.Ary{
			Len: bal,            // Biomes array length
			Ary: c.Level.Biomes, // Biomes
		},
		size, pk.Ary{
			Len: size,                      // Size
			Ary: pk.ByteArray(buf.Bytes()), // Data
		},
		pk.VarInt(0), // Block entities array length
	)
```

**Comment by Tnze** [comment]
For now, the `nbt` library is not supporting encoding `map`, that is Heightmaps, as `NBT_TagCompound` but support decoding to them.

So It takes time to implement and test them. 🕊

**Comment by wildrun0** [comment]
Okay, got it

**Comment by wildrun0** [comment]
Should I report the latest issues with chunks?

**Comment by Tnze** [comment]
As you want

**Comment by wildrun0** [comment]
Okay
After latest commit I getting this error:
```
panic: interface conversion: int32 is not packet.FieldEncoder: missing method WriteTo

goroutine 7 [running]:
github.com/Tnze/go-mc/net/packet.Ary.WriteTo(0xfb4320, 0xc0001d1f40, 0xfabc40, 0xc0000a6828, 0x104d3c0, 0xc000098ea0, 0x2, 0x0, 0x0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402054205-6558738f48a8/net/packet/util.go:33 +0x1a9
github.com/Tnze/go-mc/net/packet.(*Builder).WriteField(0xc000098ea0, 0xc0001db5c0, 0x1, 0x1)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402054205-6558738f48a8/net/packet/builder.go:11 +0x87
github.com/Tnze/go-mc/net/packet.Marshal(0x22, 0xc0001db7d0, 0xa, 0xa, 0xc00009e7c0, 0x5, 0x0, 0x0)
        C:/Users/laptop_machine/go/pkg/mod/github.com/!tnze/go-mc@v1.16.5-pre2.0.20210402054205-6558738f48a8/net/packet/packet.go:20 +0xae
main.ExampleColumn_send(0x10500f8, 0xc000006048, 0x104d380, 0xc000044120, 0x104d7c0, 0xc000006048, 0x0, 0xff3d7b, 0x16)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/chunk_worker.go:65 +0x688
main.handlePlaying(0x10500f8, 0xc000006048, 0x104d380, 0xc000044120, 0x104d7c0, 0xc000006048, 0x0, 0x242)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:249 +0xa72
main.acceptConn(0x10500f8, 0xc000006048, 0x104d380, 0xc000044120, 0x104d7c0, 0xc000006048, 0x0)
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:130 +0x1e9
created by main.main
        C:/Users/laptop_machine/Desktop/Minecraft-golang-server/main.go:93 +0x185
exit status 2
```

**Comment by Tnze** [comment]
This is not a bug. This is a misuse.

Fields you marshaling have to be `pk.FieldEncoder`, e.g. `pk.Int`, `pk.VarInt`, `pk.Byte`, etc.
So the type of `c.Level.Biomes` is `[]int32`, but we need `[]pk.Int` or `[]pk.VarInt` which I' am not sure now. I'm protected by GFW from wiki.vg now.

**Comment by wildrun0** [comment]
Okay I got it. But now I getting another error: `uint8 is not packet.FieldEncoder: missing method WriteTo`

**Comment by Tnze** [comment]
Maybe you can solve this problem by your self (?)

**Comment by wildrun0** [comment]
Oh, okay. Sorry for taking your time!
